---
# tasks file for sample-role-2
    - name: role2
      debug: msg="{{ variable2 }}"

    - name: Ansible create file if it doesn't exist example
      file:
        path: "~/playbook2.txt"
        state: touch
